const f=(label,name,widget='string',extra={})=>({label,name,widget,...extra});
const rich=(label,name,extra={})=>f(label,name,'richtext',{modes:['rich_text','raw'],sanitize_preview:true,...extra});
const image=(label,name,extra={})=>f(label,name,'image',{allow_multiple:false,...extra});
export function cmsConfig(repo,branch='main'){
 return {load_config_file:false,backend:{name:'github',repo:repo||'',branch},publish_mode:'editorial_workflow',media_folder:'public/uploads',public_folder:'/uploads',logo_url:'/assets/tidyhavens-logo.png',display_url:'/',show_preview_links:true,slug:{encoding:'ascii',clean_accents:true,sanitize_replacement:'-'},collections:[
 {name:'posts',label:'Blog posts',label_singular:'Post',folder:'content/posts',create:true,delete:true,extension:'json',format:'json',slug:'{{slug}}',preview_path:'blog/{{slug}}/',summary:'{{title}} · {{category}}',sortable_fields:['date','title'],fields:[
 f('Title','title'),f('Article date','date','datetime',{format:'YYYY-MM-DD',date_format:'MMM D, YYYY',time_format:false,picker_utc:true}),f('Category','category','select',{options:['Desk Gadgets & Accessories','Home Office & Desk Setups','Anime Desk & Room Décor']}),f('Short description','description','text',{hint:'Used on the homepage and in search descriptions.'}),image('Cover image','image'),f('Describe the cover image','imageAlt'), f('Show on website','visible','boolean',{default:true,hint:'Turn off and publish to remove this article from the public website. Save drafts with the workflow controls.'}),f('Show affiliate disclosure','affiliate','boolean',{default:false}),
 f('Featured Products','products','list',{collapsed:true,summary:'{{fields.name}}',required:false,fields:[f('Product ID','id'),f('Product name','name'),f('Benefit (short)','benefit'),image('Product image','image',{required:false}),f('Image description','alt','string',{required:false}),f('Product or affiliate link','url','string',{pattern:['^https://[^\\s]+$','Use a complete https:// link.']})]}),
 f('Article sections','blocks','list',{collapsed:true,min:1,summary:'{{fields.heading}}{{fields.name}}',hint:'Add sections, then drag their handles to reorder them.',types:[
 {label:'Text section',name:'text',widget:'object',summary:'{{fields.heading}}',fields:[f('Heading','heading','string',{required:false}),rich('Text','body')]},
 {label:'Image',name:'image',widget:'object',fields:[image('Image','image'),f('Image description','alt'),f('Caption','caption','string',{required:false})]},
 {label:'Product',name:'product',widget:'object',summary:'{{fields.name}}',fields:[f('Product name','name'),image('Product image','image',{required:false}),f('Image description','alt','string',{required:false}),rich('Why this product fits','description'),f('Product or affiliate link','url','string',{pattern:['^https://[^\\s]+$','Use a complete https:// link.']}),f('Button label','button','string',{default:'View product'})]},
 {label:'Shop the Look',name:'shop-the-look',widget:'object',summary:'Shop the look grid',fields:[f('Heading','heading','string',{default:'Shop the Look',required:false})]},
 {label:'Product Reference',name:'product-ref',widget:'object',summary:'Product: {{fields.id}}',fields:[f('Product ID','id'),rich('Editorial Text','body')]}
 ]})]},
 {name:'settings',label:'Homepage & branding',delete:false,files:[{label:'Homepage',name:'homepage',file:'content/settings.json',fields:[f('Headline lines','headline','list',{min:1,max:3,field:f('Line','line'),hint:'The final line uses the accent style.'}),f('Introduction','intro','text'),image('Main homepage image','heroImage'),f('Main image description','heroAlt'),image('Logo','logo'),f('Pinterest profile URL','pinterest','string',{pattern:['^https://[^\\s]+$','Use a complete https:// link.']})]}]}
 ]};
}
